apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd  # Argo CD's namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/ruihukuang/Argo_Helm_Xgboost_EKS.git'
    targetRevision: HEAD
    path: my-app  # Path to your Helm chart in the repository
    helm:
      valueFiles:
        - values.yaml  # Path to your custom values.yaml file in the Git repository
      parameters:
        - name: app.image
          value: public.ecr.aws/v3z5t7a3/my_repo_xgboost_test:${{ env.IMAGE_TAG }}
  destination:
    server: ${{ env.EKS_Endpoint }}
    namespace: my-app-test  # Namespace where your app will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
