nginx:
  namespace: my-app-test
  worker_connections: 1024
app:
  namespace: my-app-test
  image: public.ecr.aws/v3z5t7a3/my_repo_xgboost_test:a80cbb82281f0169507a08593169940925e9bb54_xgboost
  replicas: 4
  resources:
    requests:
      memory: "300Mi"
      cpu: "300m"
    limits:
      memory: "350Mi"
      cpu: "500m"
