nginx:
  namespace: my-app-test
  worker_connections: 1024
app:
  namespace: my-app-test
  image: xxx
  replicas: 4
  resources:
    requests:
      memory: "300Mi"
      cpu: "300m"
    limits:
      memory: "350Mi"
      cpu: "500m"
