apiVersion: v1
kind: Service
metadata:
  name: gunicorn-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: gunicorn
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8000
