apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.appLabel }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
