apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.appLabel }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.app.appLabel }}
