apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.serviceName }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: {{ .Values.nginx.appLabel }}
