apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.nginx.namespace }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: nginx
