apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.nginx.namespace }}
data:
  nginx.conf: |
    events {
      worker_connections {{ .Values.nginx.worker_connections}};
    }
    http {
      upstream gunicorn_upstream {
        server gunicorn-service:81;  # Replace with your Gunicorn service name
      }
      server {
        listen 8081; if your NGINX container is configured to listen on port 8081 (as specified by containerPort: 8081 in the Deployment), then the listen directive inside the NGINX configuration file should also be set to 8081
        location / {
          proxy_pass http://gunicorn_upstream; # Must match the upstream block name
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
