apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.nginx.namespace }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream gunicorn_upstream {
        server gunicorn-service:80;  # Replace with your Gunicorn service name
      }
      server {
        listen 80;
        location / {
          proxy_pass http://gunicorn_upstream; # Must match the upstream block name
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
