apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.configName }}
  namespace: {{ .Values.nginx.namespace }}
data:
  nginx.conf: |
    upstream backend {
        server {{ .Values.app.serviceName }}:80;
    }
    server {
        listen 443 ssl;
        server_name yourdomain.com;
        ssl_certificate /path/to/fullchain.pem;
        ssl_certificate_key /path/to/privkey.pem;
        location / {
            proxy_pass http://backend;
        }
