apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nginx.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.appLabel }}
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ .Values.nginx.configName }}
